name: 'Hello World'
description: 'Greet someone...'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  files:
    description: 'Assets to format'
    required: true
  separator:
    description: 'The character used to seperate file names'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash   
    - run: |
        cd $GITHUB_ACTION_PATH
        ls
        python print('Welcome to Real Python!')
        chmod +x scripts/run.py
        python scripts/run.py ${{ inputs.files }} ${{ inputs.separator }}
        echo SEPARATOR ${{ inputs.separator }}.
        echo FILES ${{ inputs.files }}.
      shell: bash